### PR TITLE
Update julia_socket.jl

### PR DESCRIPTION
**Pull request by sje30**
simple name change of the TCPServer type.

### CODE REVIEW

**Comment by yihui** [comment]
When did that change in Julia?

**Comment by sje30** [comment]
It was changed Aug 2014:

  https://github.com/JuliaLang/julia/commit/24714f26ecad704e017d66eeff846c16b9c92b6e

(Julia 0.4 is likely to come out in the coming days/weeks).


S

**Comment by yihui** [comment]
Okay, then I'll merge it after Julia 0.4 is released. Thanks!

**Comment by sje30** [comment]
Julia 0.4 is now out...

http://julialang.org/blog/2015/10/julia-0.4-release/

**Pull request merged**
